package com.ack.productconsumerapi.repository.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Setter;
import org.springframework.data.annotation.Id;

import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

@Setter
@DynamoDBTable(tableName = "Product")
public class ProductEntity implements Serializable {

    @Id
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey
    private String id;

    private String name;
    private String description;
    private String advertiserId;
    private Integer likeCount = 0;
    private Integer disLikeCount = 0;
    private Integer watchCount = 0;
    private Map<String, Long> rates = new HashMap<>();

    @DynamoDBAutoGeneratedTimestamp
    private Date createdDate;

    @DynamoDBHashKey(attributeName = "Id")
    public String getId(){
        return id;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    @DynamoDBAttribute
    public String getAdvertiserId() {
        return advertiserId;
    }

    @DynamoDBAttribute
    public Date getCreatedDate() {
        return createdDate;
    }

    @DynamoDBAttribute
    public Integer getLikeCount() {
        return likeCount;
    }

    @DynamoDBAttribute
    public Integer getDisLikeCount() {
        return disLikeCount;
    }

    @DynamoDBAttribute
    public Integer getWatchCount() {
        return watchCount;
    }

    @DynamoDBAttribute
    public Map<String, Long> getRates() {
        return rates;
    }
}
